name: tybot

services:
  client:
    image: tybot-client:0.0.0
    ports:
      - 3000:80

  server:
    image: tybot-server:0.0.0
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - DATABASE_NAME=tybot
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_HOST=postgres
      - OLLAMA_BASE_URL=http://ollama:11434

  ollama:
    gpus: all
    image: ollama/ollama:0.17.0
    ports:
      - 11434:11434
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ./ollama:/root/.ollama

  postgres:
    image: postgres:18.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tybot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  tileserver:
    image: maptiler/tileserver-gl:v5.5.0
    ports:
      - 8080:8080
    volumes:
      - ./tileserver:/data
