name: tybot

services:
  client:
    image: tybot-client:0.0.0
    ports:
      - 3000:80

  server:
    image: tybot-server:0.0.0
    ports:
      - 8000:8000
    environment:
      - HOST=0.0.0.0
      - OLLAMA_BASE_URL=http://ollama:11434

  ollama:
    gpus: all
    image: ollama/ollama:0.15.4
    ports:
      - 11434:11434
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ./ollama:/root/.ollama
