name: CI

on:
  push:

jobs:
  check-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - run: |
          pnpm i --frozen-lockfile
          pnpm -r exec eslint
          pnpm prettier -c .

  check-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
      - run: |
          uv sync --all-packages --frozen
          uv run ruff check --no-cache
          uv run ty check --error-on-warning

  build-js:
    runs-on: ubuntu-latest
    needs: [check-js, check-py]
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - run: |
          pnpm i --frozen-lockfile
          pnpm -r build

  build-py:
    runs-on: ubuntu-latest
    needs: [check-js, check-py]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
      - run: |
          uv sync --all-packages --frozen
          uv build --all-packages --wheel
